//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Details
    {
        public string AccName { get; set; }
        public string AccPassword { get; set; }
        public string AccPhone { get; set; }
        public string AccAddress { get; set; }
        public string AccEmail { get; set; }
    }
}
