//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public string CusId { get; set; }
        public string ProId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Customer_info Customer_info { get; set; }
        public virtual Product Product { get; set; }
    }
}
