//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Details
    {
        public string OrderId { get; set; }
        public string CusId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public System.DateTime ShippedDate { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress { get; set; }
        public string ShipCity { get; set; }
        public string ShipPostalCode { get; set; }
    
        public virtual Customer_info Customer_info { get; set; }
    }
}
