//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sports_Info
    {
        public string SpoId { get; set; }
        public string SpoName { get; set; }
        public string SpoCategory { get; set; }
        public string SpoGears { get; set; }
        public string SpoDescription { get; set; }
    }
}
