//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {

        public string userId { get; set; }
       
        [DataType("password")]
        public string password { get; set; }
     
        public string first_name { get; set; }
       
        public string last_name { get; set; }
       
        public string email { get; set; }
    
        public string UserAddress { get; set; }
      
        public string UserMobile { get; set; }
    
        public virtual Customer_info Customer_info { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
